src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     */
    private $rating;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $last_updated_at;

    /**
     * @ORM\OneToOne(targetEntity=MovieWatched::class, mappedBy="comment", cascade={"persist", "remove"})
     */
    private $movieWatched;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comment")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(): self
    {
        $dateNow = new DateTimeImmutable();

        $this->created_at = $dateNow;

        return $this;
    }

    public function getLastUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->last_updated_at;
    }

    public function setLastUpdatedAt(): ?self
    {
        $dateNow = new DateTimeImmutable();

        $this->last_updated_at = $dateNow;

        return $this;
    }

    public function getMovieWatched(): ?MovieWatched
    {
        return $this->movieWatched;
    }

    public function setMovieWatched(MovieWatched $movieWatched): self
    {
        // set the owning side of the relation if necessary
        if ($movieWatched->getComment() !== $this) {
            $movieWatched->setComment($this);
        }

        $this->movieWatched = $movieWatched;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

templates/_partials/_comment_form.html.twig
    {{ form_start(form) }}

    <div class=" form-control form-control--large max-w-4xl">

        <div class="form-item w-full">
            <label>Commentaire </label>
            {{ form_errors(form.comment) }}
            {{ form_widget(form.comment, {'attr': {'rows': '10'} }) }}
        </div>

        <div class="form-item">
            <label>Note /10 </label>
            {{ form_errors(form.rating) }}
            {{ form_widget(form.rating) }}
        </div>


        <button class="neon_button--pink">
            Valider
        </button>
    </div>

    {{ form_end(form) }}

templates/_partials/_stars.html.twig
{% set stars = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] %}

<div class="flex flex-row whitespace-nowrap flex-nowrap">

{% for star in stars %}
{% if star < rating %}
    <i class=" fas fa-star text-neon-yellow "></i>

    {% else %}
        <i class="fas fa-star text-black"></i>
    {% endif %}

{% endfor %}
</div>

templates/_partials/favicons.html.twig
<link rel="apple-touch-icon" sizes="180x180" href="/favicons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicons/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicons/favicon-16x16.png">
<link rel="manifest" href="/favicons/site.webmanifest">
<link rel="mask-icon" href="/favicons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/favicons/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="/favicons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

templates/_partials/neon_logo.html.twig
{% if app.user is null %}
    {% set homePath = "home" %}
{% else %}
    {% set homePath = "user_home" %}
{% endif %}
<a href="{{ path(homePath) }}">
    <h1 class="neon_sign font-neon sm:py-4 mx-auto md:mx-0 ">
            <span class="neon_sign-firstLine"><span class="neon_sign-flicker--5">M</span>o<span
                        class="neon_sign-flicker--2">v</span>ies</span>
        <span class="neon_sign-secondLine">Reca<span class="neon_sign-flicker--3">l</span>l</span>
    </h1>
    <hr class="neon-bar mt-4 sm:mt-0 mb-16">
</a>