src/Entity/Club.php
<?php

namespace App\Entity;

use App\Repository\ClubRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ClubRepository::class)
 */
class Club
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity=UserClub::class, mappedBy="club")
     */
    private $user_club;

    public function __construct()
    {
        $this->user_club = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(): self
    {
        $dateNow = new DateTimeImmutable();

        $this->created_at = $dateNow;


        return $this;
    }

    /**
     * @return Collection|UserClub[]
     */
    public function getUserClub(): Collection
    {
        return $this->user_club;
    }

    public function addUserClub(UserClub $userClub): self
    {
        if (!$this->user_club->contains($userClub)) {
            $this->user_club[] = $userClub;
            $userClub->setClub($this);
        }

        return $this;
    }

    public function removeUserClub(UserClub $userClub): self
    {
        if ($this->user_club->removeElement($userClub)) {
            // set the owning side to null (unless already changed)
            if ($userClub->getClub() === $this) {
                $userClub->setClub(null);
            }
        }

        return $this;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     */
    private $rating;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $last_updated_at;

    /**
     * @ORM\OneToOne(targetEntity=MovieWatched::class, mappedBy="comment", cascade={"persist", "remove"})
     */
    private $movieWatched;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comment")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRating(): ?int
    {
        return $this->rating;
    }

    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(): self
    {
        $dateNow = new DateTimeImmutable();

        $this->created_at = $dateNow;

        return $this;
    }

    public function getLastUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->last_updated_at;
    }

    public function setLastUpdatedAt(): ?self
    {
        $dateNow = new DateTimeImmutable();

        $this->last_updated_at = $dateNow;

        return $this;
    }

    public function getMovieWatched(): ?MovieWatched
    {
        return $this->movieWatched;
    }

    public function setMovieWatched(MovieWatched $movieWatched): self
    {
        // set the owning side of the relation if necessary
        if ($movieWatched->getComment() !== $this) {
            $movieWatched->setComment($this);
        }

        $this->movieWatched = $movieWatched;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Controller/Movie/MoviesController.php
<?php

namespace App\Controller\Movie;


use App\Form\MovieSearchType;
use App\Services\ImdbApi;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class MoviesController extends AbstractController
{
    private ImdbApi $imdbApi;

    public function __construct(ImdbApi $imdbApi)
    {
        $this->imdbApi = $imdbApi;
    }




    /**
     * @Route("/movies/search", name="movies_search")
     */
    public function searchMovies(Request $request): Response
    {
        $data = null;
        $error  = "";

        $form = $this->createForm(MovieSearchType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $searchParams = $form->getData();

            try {
                $data = $this->imdbApi->searchData($searchParams);
            } catch (\Exception $e) {
                $error = $e->getCode();
            }
        }
        return $this->render('movies/search.html.twig', [
            'user'  => $this->getUser(),
            'form'  => $form->createView(),
            'data'  => $data,
            'error' => $error
        ]);
    }





    /**
     * @Route("/movies/show/{imdbId}", name="movie_show")
     */
    public function showMovie($imdbId): Response
    {
        $error     = "";
        $movieData = $this->imdbApi->getMovieDetails($imdbId);

        return $this->render('movies/showMovie.html.twig', [
            'showType'  => "BASE",
            'movieData' => $movieData,
            'error'     => $error
        ]);
    }

}

templates/movies/show/base.html.twig
<div class="flex flex-row justify-center  sm-down:flex-col">
    <a href="{{ path('add_movie_todo', {'imdbId': movieData.id }) }}"
       class="neon_button--blue m-4 p-2 ">Liste A voir</a>

    <a href="{{ path('add_watched_movie', {'imdbId' : movieData.id}) }}"
       class="neon_button--pink  m-4 p-2 " >Liste Vu</a>
</div>

templates/movies/show/towatch.html.twig
<div class="flex flex-row justify-center sm-down:flex-col">
    <a href="{{ path('delete_movie_todo', {'id': movieTodo.id }) }}"
       class="neon_button--red m-4 p-2 " onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce film de votre watchlist ?')">Supprimer des films à voir</a>

    <a href="{{ path('add_watched_movie', {'imdbId' : movieData.id}) }}"
       class="neon_button--pink  m-4 p-2 " >Liste Vu</a>
</div>

templates/movies/show/watched.html.twig
<div class="meta-sub-wrapper">
    <div class="comment-data pb-5">
        <div class="pb-4">
            {% if movieWatched.comment.lastUpdatedAt is not null %}
                {{ movieWatched.comment.lastUpdatedAt | date('d F Y') }}
            {% else %}
                {{ movieWatched.comment.createdAt | date('d F Y') }}
            {% endif %}
        </div>
        <div class="flex justify-center pb-4 ">
            {{ include('_partials/_stars.html.twig', {rating: movieWatched.comment.rating  }) }}
        </div>

        <p class="mb-6">
            {{ movieWatched.comment.comment }}
        </p>

        {% if isEditAuthorized == true %}
            <div class="flex flex-col  items-center">

            <a href="{{ path("update_watched_movie", {id: movieWatched.id}) }}" class="neon_button--yellow w-min m-4">Modifier</a>
            <a href="{{ path("delete_watched_movie", {id: movieWatched.id}) }}" class="neon_button--red    w-min m-4" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce film de votre liste de films vus ? ?')">Supprimer</a>
            </div>

        {% endif %}
    </div>


</div>